# Generated by Django 2.1.2 on 2018-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localManagement', '0001_initial'),
        ('user', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='carta_di_credito',
            field=models.ManyToManyField(blank=True, related_name='carta_di_credito', to='user.CartaDiCredito'),
        ),
        migrations.AddField(
            model_name='commerciante',
            name='possiede_locale',
            field=models.ManyToManyField(blank=True, related_name='possiede_locale', to='localManagement.Locale'),
        ),
    ]
