# Generated by Django 2.1.3 on 2018-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181030_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='carta_di_credito',
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
