# Generated by Django 2.1.3 on 2018-11-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_utente_carta_di_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='carta_di_credito',
            field=models.ManyToManyField(blank=True, related_name='carta_di_credito', to='user.CartaDiCredito'),
        ),
    ]
