# Generated by Django 2.1.3 on 2018-11-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181122_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='carta_di_credito',
        ),
    ]
