# Generated by Django 2.1.3 on 2018-11-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_cartadicredito_utente'),
        ('accounts', '0006_remove_utente_carta_di_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='carta_di_credito',
            field=models.ManyToManyField(blank=True, related_name='carta_di_credito', to='user.CartaDiCredito'),
        ),
    ]
