# Generated by Django 2.1.3 on 2018-11-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_utente_carta_di_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='carta_di_credito',
        ),
    ]
