# Generated by Django 2.1.2 on 2018-10-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localManagement', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaDiCredito',
            fields=[
                ('cod_carta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_carta', models.CharField(max_length=16)),
                ('intestatario', models.CharField(max_length=60)),
                ('scadenza', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Carte di credito',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('cod_recensione', models.AutoField(primary_key=True, serialize=False)),
                ('voto', models.SmallIntegerField(null=True)),
                ('descrizione', models.CharField(max_length=130, null=True)),
                ('date', models.DateField()),
                ('cod_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Locale')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Utente')),
                ('p_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Commerciante')),
            ],
            options={
                'verbose_name_plural': 'Recensioni',
            },
        ),
        migrations.AlterUniqueTogether(
            name='recensione',
            unique_together={('email', 'cod_locale', 'p_iva')},
        ),
    ]
