# Generated by Django 2.1.3 on 2018-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_utente_carta_di_credito'),
        ('user', '0002_auto_20181119_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartadicredito',
            name='utente',
            field=models.ManyToManyField(blank=True, to='accounts.Utente'),
        ),
    ]
