# Generated by Django 2.1.3 on 2018-11-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cartadicredito_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartadicredito',
            name='utente',
        ),
    ]
