# Generated by Django 2.1.3 on 2018-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_utente_carta_di_credito'),
        ('user', '0004_remove_cartadicredito_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartadicredito',
            name='utente',
            field=models.ManyToManyField(blank=True, to='accounts.Utente'),
        ),
    ]
