# Generated by Django 2.1.2 on 2018-10-30 14:29

from django.db import migrations, models
import django.db.models.deletion
import localManagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiusura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_chiusura', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Chiusura',
                'verbose_name_plural': 'Chiusura',
            },
        ),
        migrations.CreateModel(
            name='CompostoDa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Composto da',
                'verbose_name_plural': 'Composto da',
            },
        ),
        migrations.CreateModel(
            name='FotoLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_locale', models.ImageField(blank=True, null=True, upload_to=localManagement.models.local_images_path, validators=[localManagement.models.validate_image_size])),
            ],
            options={
                'verbose_name_plural': 'Foto Locali',
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('cod_locale', models.AutoField(primary_key=True, serialize=False)),
                ('nome_locale', models.CharField(max_length=30)),
                ('orario_apertura', models.TimeField()),
                ('orario_chiusura', models.TimeField()),
                ('num_civico', models.CharField(max_length=10)),
                ('via', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('sito_web', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Locali',
            },
        ),
        migrations.CreateModel(
            name='Localita',
            fields=[
                ('cap', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome_localita', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Località',
                'verbose_name_plural': 'Località',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_menu', models.CharField(max_length=30)),
                ('descrizione_menu', models.CharField(max_length=200)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'Menù',
                'verbose_name_plural': 'Menù',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prodotto', models.CharField(max_length=30)),
                ('descrizione_prodotto', models.CharField(max_length=200)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('foto_prodotto', models.ImageField(blank=True, null=True, upload_to=localManagement.models.product_images_path, validators=[localManagement.models.validate_image_size])),
                ('cod_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Locale')),
            ],
            options={
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('nome_tag', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('nome_tipo', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Tipi',
            },
        ),
        migrations.AddField(
            model_name='prodotto',
            name='nome_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Tipo'),
        ),
    ]
