# Generated by Django 2.1.2 on 2018-10-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('localManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='richiede_prodotto',
            field=models.ManyToManyField(blank=True, related_name='richiede_prodotto', through='order.RichiedeP', to='order.OrdineInAttesa'),
        ),
        migrations.AddField(
            model_name='menu',
            name='cod_locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Locale'),
        ),
        migrations.AddField(
            model_name='menu',
            name='composto_da_prodotti',
            field=models.ManyToManyField(blank=True, related_name='composto_da_prodotti', through='localManagement.CompostoDa', to='localManagement.Prodotto'),
        ),
        migrations.AddField(
            model_name='menu',
            name='richiede_menu',
            field=models.ManyToManyField(blank=True, related_name='richiede_menu', through='order.RichiedeM', to='order.OrdineInAttesa'),
        ),
        migrations.AddField(
            model_name='locale',
            name='cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Localita'),
        ),
        migrations.AddField(
            model_name='locale',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='locale_tag', to='localManagement.Tag'),
        ),
        migrations.AddField(
            model_name='fotolocale',
            name='cod_locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Locale'),
        ),
        migrations.AddField(
            model_name='compostoda',
            name='cod_locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Locale'),
        ),
        migrations.AddField(
            model_name='compostoda',
            name='nome_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_nome_menu', to='localManagement.Menu'),
        ),
        migrations.AddField(
            model_name='compostoda',
            name='nome_prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Prodotto'),
        ),
        migrations.AddField(
            model_name='chiusura',
            name='cod_locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Locale'),
        ),
        migrations.AlterUniqueTogether(
            name='prodotto',
            unique_together={('cod_locale', 'nome_prodotto')},
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('cod_locale', 'nome_menu')},
        ),
        migrations.AlterUniqueTogether(
            name='locale',
            unique_together={('nome_locale', 'cap')},
        ),
        migrations.AlterUniqueTogether(
            name='compostoda',
            unique_together={('cod_locale', 'nome_menu', 'nome_prodotto')},
        ),
        migrations.AlterUniqueTogether(
            name='chiusura',
            unique_together={('cod_locale', 'giorno_chiusura')},
        ),
    ]
