# Generated by Django 2.1.3 on 2018-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localManagement', '0002_auto_20181030_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='prezzo_di_spedizione',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chiusura',
            name='giorno_chiusura',
            field=models.CharField(choices=[('Lunedì', 'Lunedì'), ('Martedì', 'Martedì'), ('Mercoledì', 'Mercoledì'), ('Giovedì', 'Giovedì'), ('Venerdì', 'Venerdì'), ('Sabato', 'Sabato'), ('Domenica', 'Domenica')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='locale',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
