# Generated by Django 2.1.3 on 2018-11-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localManagement', '0004_auto_20181121_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='richiede_menu',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='richiede_prodotto',
        ),
    ]
