# Generated by Django 2.1.2 on 2018-10-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localManagement', '0001_initial'),
        ('user', '0001_initial'),
        ('accounts', '0002_auto_20181030_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineInAttesa',
            fields=[
                ('cod_ordine', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('orario_richiesto', models.TimeField()),
                ('metodo_pagamento', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Ordini in Attesa',
            },
        ),
        migrations.CreateModel(
            name='RichiedeM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.SmallIntegerField()),
                ('cod_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Locale')),
            ],
            options={
                'verbose_name_plural': 'Richiede Menù',
            },
        ),
        migrations.CreateModel(
            name='RichiedeP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.SmallIntegerField()),
                ('cod_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localManagement.Locale')),
            ],
            options={
                'verbose_name_plural': 'Richiede Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Accettato',
            fields=[
                ('cod_ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cod_ordine_accettato', serialize=False, to='order.OrdineInAttesa')),
                ('consegnato', models.BooleanField(default=False)),
                ('descrizione', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ordini Accettati',
            },
        ),
        migrations.CreateModel(
            name='Rifiutato',
            fields=[
                ('cod_ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cod_ordine_rifiutato', serialize=False, to='order.OrdineInAttesa')),
                ('descrizione', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ordini Rifiutati',
            },
        ),
        migrations.AddField(
            model_name='richiedep',
            name='cod_ordine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrdineInAttesa'),
        ),
        migrations.AddField(
            model_name='richiedep',
            name='nome_prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_nome_prodotto', to='localManagement.Prodotto'),
        ),
        migrations.AddField(
            model_name='richiedem',
            name='cod_ordine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrdineInAttesa'),
        ),
        migrations.AddField(
            model_name='richiedem',
            name='nome_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_nome_menu_1', to='localManagement.Menu'),
        ),
        migrations.AddField(
            model_name='ordineinattesa',
            name='cod_carta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.CartaDiCredito'),
        ),
        migrations.AddField(
            model_name='ordineinattesa',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Utente'),
        ),
        migrations.AlterUniqueTogether(
            name='richiedep',
            unique_together={('cod_ordine', 'cod_locale', 'nome_prodotto')},
        ),
        migrations.AlterUniqueTogether(
            name='richiedem',
            unique_together={('cod_ordine', 'cod_locale', 'nome_menu')},
        ),
        migrations.AlterUniqueTogether(
            name='ordineinattesa',
            unique_together={('email', 'data')},
        ),
    ]
