# Generated by Django 2.1.3 on 2018-11-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localManagement', '0005_auto_20181128_0954'),
        ('order', '0003_remove_ordineinattesa_recapito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordineinattesa',
            name='menues',
            field=models.ManyToManyField(blank=True, null=True, through='order.RichiedeM', to='localManagement.Menu'),
        ),
        migrations.AddField(
            model_name='ordineinattesa',
            name='prodotti',
            field=models.ManyToManyField(blank=True, null=True, through='order.RichiedeP', to='localManagement.Prodotto'),
        ),
    ]
