# Generated by Django 2.1.3 on 2018-11-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20181128_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineinattesa',
            name='metodo_pagamento',
            field=models.CharField(choices=[('CARTA DI CREDITO', 'carta di credito'), ('ALLA CONSEGNA', 'alla consegna')], max_length=30),
        ),
    ]
