# Generated by Django 2.1.3 on 2018-11-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20181128_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineinattesa',
            name='metodo_pagamento',
            field=models.CharField(choices=[('carta di credito', 'carta di credito'), ('alla consegna', 'alla consegna')], max_length=30),
        ),
    ]
