# Generated by Django 2.1.3 on 2018-12-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181128_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accettato',
            name='cod_ordine',
        ),
        migrations.RemoveField(
            model_name='rifiutato',
            name='cod_ordine',
        ),
        migrations.AddField(
            model_name='ordineinattesa',
            name='accettato',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ordineinattesa',
            name='consegnato',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ordineinattesa',
            name='descrizione',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Accettato',
        ),
        migrations.DeleteModel(
            name='Rifiutato',
        ),
    ]
